config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get '/sitemap', to: 'sitemaps#index', :defaults => {:format => 'xml'}
  # get 'laws/:id', to: 'laws#show'
  resources :laws, only: [:show, :new, :create]
  get 'votes/:id', to: 'votes#show'
  get '/dashboard', to: 'pages#dashboard'
  get '/get_followed_deputies', to: 'deputies#get_followed_deputies'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :deputies, only: [:show] do
    collection do
      get :results
    end
    member do
      get :like
      get :like_guest
      post :follow
      get :follow_guest
      get :is_followed
    end
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/deputy.rb
class Deputy < ApplicationRecord
  has_many :positions, dependent: :destroy
  has_many :laws, through: :positions
  acts_as_votable
  include AlgoliaSearch

  extend FriendlyId
  friendly_id :full_name, use: :slugged

  algoliasearch per_environment: true do
    attribute :last_name, :first_name, :slug, :id
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def prettify_job
    if self.job.include?("@xmlns:xsi")
      self.job = "Inconnue"
      self.save
    end
  end

  def prettify_party
    if self.party.include?("N/A")
      self.party = "Parti non renseigné"
      self.save
    end
  end

  def prettify_birth_place
    if self.birth_place.include?("@xmlns:xsi")
      self.birth_place = "Inconnue"
      self.save
    end
  end

  def prettify_revenue
    if self.revenue.include?("@xmlns:xsi")
      self.revenue = "Déclaration de revenu indisponible"
      self.save
    end
  end

  def prettify
    self.prettify_job
    self.prettify_party
    self.prettify_revenue
    self.prettify_birth_place
  end

  def participationRate
    positionsCount = self.positions.count
    if positions.count > 0
      absentVotes = self.positions.select { |position| position.votant == false }
      absentCount = absentVotes.count
      ((1 - absentCount.fdiv(positionsCount)) * 100).truncate.fdiv(100)
    else
      0
    end
  end

  def frondingRate
    (100 - self.fronding).fdiv(100)
  end

  def yearlyRevenue
    self.yearly_revenue / 1000
  end

  def filteredParticipationRate(tag)
    positions = self.positions.select { |position| position.law.tag_list.include? tag }
    positionsCount = positions.count
    absentVotes = positions.select { |position| position.votant == false }
    absentCount = absentVotes.count
    ((1 - absentCount.fdiv(positionsCount)) * 100).truncate.fdiv(100)
  end

  def make_img_https
    self.img = self.img.gsub('http', 'https')
    self.save
  end

end

app/controllers/deputies_controller.rb
require 'open-uri'
require 'csv'

class DeputiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:results, :show]

  def show
    @deputy = Deputy.friendly.find(params[:id])
    @tag = params[:tag]
    if @tag
      positions = @deputy.positions.sort_by { |position| Law.find(position.law_id).last_status_update }.reverse
      @positions = positions.select { |position| position.law.tag_list.include? params[:tag] }
    else
      @positions = @deputy.positions.sort_by { |position| Law.find(position.law_id).last_status_update }.reverse
    end
    @user = current_user
    @topTags = getTopTags(5)
  end

  def getTopTags(number)
    topTags = []
    ActsAsTaggableOn::Tag.most_used(number).each do |tag|
      topTags << tag.name.split(" ").reject{ |word| word == "-"}.map(&:capitalize).join
    end
    return topTags
  end

  def like
    @user = current_user
    @position = Position.find(params[:position_id])
    @deputy = Deputy.friendly.find(params[:id])
    if params[:like] == "true"
      @user.likes @position
    else
      @user.dislikes @position
    end
    flash[:notice] = "Merci d'avoir voté !"
    respond_to do |format|
      format.html
      format.json { render json: { likes: @position.get_likes.size,
                                    dislikes: @position.get_dislikes.size } }
    end
  end

  def like_guest
    @user = current_user
    @position = Position.find(params[:position_id])
    @deputy = Deputy.friendly.find(params[:id])
    if params[:like] == "true"
      @user.likes @position
    else
      @user.dislikes @position
    end
    flash[:notice] = "Merci d'avoir voté !"
    redirect_to deputy_path(@deputy)
  end

  def follow
    @user = current_user
    @deputy = Deputy.friendly.find(params[:id])
    if @user.voted_for?(@deputy)
      @deputy.unliked_by @user
    else
      @deputy.liked_by @user
    end
    respond_to do |format|
      format.html
      format.json { render json: { is_followed: @user.voted_for?(@deputy) } }
    end
  end

  def follow_guest
    @user = current_user
    @deputy = Deputy.friendly.find(params[:id])
    @deputy.liked_by @user
    redirect_to deputy_path(@deputy)
  end

  def is_followed
    @deputy = Deputy.friendly.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: { is_followed: @user.voted_for?(@deputy),
                                   deputies: self.followedDeputies } }
    end
  end

  def get_followed_deputies
    respond_to do |format|
      format.html
      format.json { render json: { deputies: self.followedDeputies } }
    end
  end
  
  def results
    query = params[:query]
    url = "https://api-adresse.data.gouv.fr/search/?q=#{URI.escape(query)}"
    redirect_to root_path and return if JSON.parse(open(url).read)["features"].empty?

    citycode = JSON.parse(open(url).read)["features"][0]["properties"]["citycode"]

    file_path = Rails.root.join("db/csv", "circonscriptions.csv")
    options = { col_sep: ";", headers: :first_row }
    circo = ""
    dep = ""
    CSV.foreach(file_path, options).with_index do |row, i|
      unless row[3].nil?
        if row[3].include?(citycode)
          dep = row[1]
          circo = row[2]
        end
      end
    end
    @deputy = Deputy.where(circonscription: circo.to_i, department: dep.to_i).first
    redirect_to root_path and return if @deputy.nil?
    redirect_to deputy_path(@deputy)
  end
end

app/views/deputies/_categories.html.erb
<ul class="categorie-container top">
  <% @topTags.each do |tag| %>
    <li class="categorie-label <%= tag %>">
      #<%= tag %>
    </li>
  <% end %>
</ul>

app/views/deputies/_charts.html.erb
          <% if @tag %>
            <p class="hidden filtered-participation-rate"><%= @deputy.filteredParticipationRate(@tag) %></p>
            <%= link_to deputy_path(@deputy) do %>
              <span class="categorie-label-top"><%= @tag.split(" ").reject{ |word| word == "-"}.map(&:capitalize).unshift("#").join %>
                <i class="fas fa-times"></i>
              </span>
            <% end %>
            <!-- <div class="chart-details-container">
              <div class="chart-details-card">
                <p>Lois analysées</p>
                <div class="chart-details-card-figure">
                  <h3><%= @positions.count %></h3>
                </div>
              </div>
              <div class="chart-details-card last">
                <p>Taux de présence sur le sujet </p>
                <div class="chart-details-card-figure">
                  <div id="filtered" class="filtered-chart"></div>
                </div>
              </div>
            </div> -->
          <% else %>
            <p id="filter-paragraph"><strong>Tags les plus consultés</strong></p>
            <ul class="categorie-container top">
              <% @topTags.each do |tag| %>
                <%= link_to deputy_path(@deputy, tag: tag) do %>
                  <li class="categorie-label">
                    <%= tag.split(" ").reject{ |word| word == "-"}.map(&:capitalize).unshift("#").join %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          <% end %>

app/views/deputies/_contactbutton.html.erb
<div class="contact-button">
  <% if @deputy.email != "N/A" %>
    <a class="button button-primary contact width-grow" href="mailto:<%= @deputy.email %>?body=%0D%0A%0D%0AJe vous ai contacté grâce à MonDéputé.info (https://www.mondepute.info/)" target="blank">Contacter</a>
  <% end %>
  <a href=""></a>
</div>

app/views/deputies/_deputyposition.html.erb
<% if position.deputy_position == "nonVotant" %>
  <h4>Non votant lors du vote</h4>
<% elsif position.deputy_position == "Absent" %>
  <h4>Absent lors du vote</h4>
<% elsif position.deputy_position == "abstention" %>
  <h4>S'est abstenu lors du vote</h4>
<% else %>
  <h4>A voté <%= position.deputy_position %></h4>
<% end %>

app/views/deputies/_followbutton.html.erb
<div class="follow-button">
  <% if user_signed_in? %>
    <%= link_to "Suivre", follow_deputy_path(@deputy), method: 'get', class: 'button button-primary follow width-grow' %>
  <% else %>
    <%= link_to "Suivre", follow_guest_deputy_path(@deputy), method: 'get', class: 'button button-primary follow width-grow' %>
  <% end %>
</div>

app/views/deputies/_likebuttons.html.erb
          <% if user_signed_in? %>
              <div>
                <%= link_to like_deputy_path(@deputy, position_id: position.id, like: true) do %>
                  <i class="far fa-thumbs-up <%= @user.liked? position %>" 
                    data-deputyid="<%= @deputy.id %>"
                    data-positionid="<%= position.id %>"
                    data-action="click->like#update"
                    data-target="like.likeButton"></i>
                <% end %>
                <p class="green" data-target="like.likeCount"><%= position.cached_votes_up %></p>
              </div>
              <div class="thumb-down">
                <%= link_to like_deputy_path(@deputy, position_id: position.id, like: false) do %>
                  <i class="far fa-thumbs-down <%= @user.disliked? position %>"
                    data-deputyid="<%= @deputy.id %>"
                    data-positionid="<%= position.id %>"
                    data-action="click->like#update"
                    data-target="like.dislikeButton"></i>
                <% end %>
                <p class="red" data-target="like.dislikeCount"><%= position.cached_votes_down %></p>
              </div>
          <% else %>
              <div>
                <%= link_to like_guest_deputy_path(@deputy, position_id: position.id, like: true) do %>
                  <i class="far fa-thumbs-up"></i>
                <% end %>
                <p class="green"><%= position.cached_votes_up %></p>
              </div>
              <div class="thumb-down">
                <%= link_to like_guest_deputy_path(@deputy, position_id: position.id, like: false) do %>
                  <i class="far fa-thumbs-down"></i>
                <% end %>
                <p class="red"><%= position.cached_votes_down %></p>
              </div>
          <% end %>

app/views/deputies/_moreinfo.html.erb
<% if position.law.content == "" %>
  <a href="<%= position.law.ressource_link %>" class="more-info" target="blank">
    Plus d'informations
  </a>
<% else %>
  <a href="" class="more-info" data-toggle="modal" data-target="#modal-<%= position.law.id %>">
    Plus d'informations
  </a>
<% end %>

app/views/deputies/_occupationcontainer.html.erb
<% if @deputy.entry_date %>
  <p>A l'assemblée depuis le <%= @deputy.entry_date.strftime('%d/%m/%Y') %></p>
<% end %>
<% if @deputy.job %>
  <p>Profession précédente : <%= @deputy.job %></p>
<% else %>
  <p>Pas de profession précédente connue</p>
<% end %>
<% if @deputy.revenue = "Déclaration de revenu indisponible" %>
  <p><%= @deputy.revenue %></p>
<% else %>
  <a href="<%= @deputy.revenue %>" target="blank">Consulter sa déclaration de revenus</a>
<% end %>

app/views/deputies/_revenuecontainer.html.erb
<% if @deputy.yearlyRevenue > 0%>
  <p>Moyenne des revenus annuels (3 dernières années)</p> 
  <h3><span data-toggle="tooltip" data-placement="right" title="Les revenus sont calculés sur les trois dernières années déclarées auprès de la Haute Autorité pour la Transparence de la Vie Publique"><%= number_with_delimiter( @deputy.yearlyRevenue, :delimiter => ' ') %> k€</span></h3>
  <a href="<%= @deputy.revenue %>" target="blank">Consulter sa déclaration de revenus</a>
<% else %>
  <p>Nous n'avons pas réussi à calculer ses revenus</p>
  <a href="<%= @deputy.revenue %>" target="blank">Consulter sa déclaration de revenus</a>
<% end %>

app/views/deputies/_socialcontainer.html.erb
<% if @deputy.facebook != "N/A" %>
  <a href="https://www.facebook.com/<%= @deputy.facebook %>" target="blank"><i class="fab fa-facebook-f"></i></a>
<% end %>
<% if @deputy.twitter != "N/A" %>
  <a href="https://twitter.com/<%= @deputy.twitter %>" target="blank"><i class="fab fa-twitter"></i></a>
<% end %>
<% if @deputy.email != "N/A" %>
  <a href="mailto:<%= @deputy.email %>" target="blank"><i class="far fa-envelope"></i></a>
<% end %>
<% if @deputy.website != "N/A" %>
  <a href="http://<%= @deputy.website %>/" target="blank"><i class="fas fa-globe"></i></a>
<% end %>

app/views/deputies/show.html.erb
<%= content_for(:title) { "#{@deputy.first_name} #{@deputy.last_name} - Député du #{@deputy.department}" } %>
<%= content_for(:image_url) { @deputy.img } %>
<%= content_for(:image_width) { "150" } %>
<%= content_for(:image_height) { "192" } %>
<%= content_for(:content) { "Découvrez les positions de votes de #{@deputy.first_name} #{@deputy.last_name} à l'Assemblée Nationale sur www.mondepute.info" } %>


<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId            : '2642641032621465',
      autoLogAppEvents : true,
      xfbml            : true,
      version          : 'v7.0'
    });
  };
</script>

<script async defer src="https://connect.facebook.net/fr_FR/sdk.js"></script>

<div class="container-deputy content-wrapper ">
  <div class="deputy-card", data-id="<%= @deputy.id %>", data-name='<%= "#{@deputy.first_name} #{@deputy.last_name}" %>', data-img=<%= @deputy.img %>>
    <div class="deputy-card-container">
      <div class="deputy-card-avatar-container avatar-bordered">
        <img src="<%= @deputy.img %>" alt="" class="avatar-bordered">
        <div class="deputy-card-avatar-container-details">
          <h1><%= @deputy.first_name %> <%= @deputy.last_name %></h1>
          <h4><%= @deputy.party %></h4>
        </div>
      </div>
      <div class="deputy-details-container occupation">
        <%= render 'occupationcontainer' %>
      </div>
      <div class="deputy-card-social-container">
        <%= render 'socialcontainer' %>
      </div>

      <!-- <div class="deputy-details-container revenue">
        <%= render 'revenuecontainer' %>
      </div>
      <div class="deputy-card-chart-container">
        <p>Taux de présence à l'assemblée</p>
        <div class="chart" id="presence"></div>
      </div>
      <div class="deputy-card-chart-container">
        <p>Taux de votes en accord avec son parti</p>
        <div class="chart" id="fronde"></div>
      </div> -->
    </div>
    <%= render 'contactbutton' %>
  </div>

  <div class="laws">
    <div class="laws-top">
      <div class="categories-list">
        <%= render 'categories' %>
      </div>
    </div>
    <% @positions.each do |position| %>
      <% if position.deputy_position == nil %>
        <% position.deputy_position = "Absent" %>
      <% end %>
      <div class="law-card <%= position.deputy_position.downcase %> <%= position.law.write_tag_list %>">
        <div class="law-card-details">
          <h3><%= position.law.title.truncate(110, separator: ' ') %></h3>
          <p><strong><%= position.law.current_status %> le <%= position.law.last_status_update %></strong>
            - <%= position.law.pour %> votes pour,
            <%= position.law.contre %> votes contre,
            <%= position.law.abstenu %> abstentions
          </p>
          <%= render 'moreinfo', :position => position %>
          <ul class="categorie-container">
            <% position.law.generate_tag_list.each do |tag|%>
              <li class="categorie-label <%= tag %>">#<%= tag %></li>
            <% end %>
          </ul>
        </div>

        <div class="law-card-interaction-card">
          <%= render 'deputyposition', :position => position %>
          <p class="avis">Donnez votre avis</p>
          <div class="interaction-like" data-controller="like">
            <%= render 'likebuttons', :position => position %>
          </div>
          <div class="share-buttons">
            <%= social_share_button_tag("#{@deputy.first_name} #{@deputy.last_name}", url: "http://mondepute.info/deputies/#{@deputy.slug}", image: "#{@deputy.img}", desc: "Découvrez les positions de votes de #{@deputy.first_name} #{@deputy.last_name} à l Assemblée Nationale sur www.mondepute.info") %>
          </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="modal-<%= position.law.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-image"></div>
            <div class="modal-content"><div>
              <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel"><%= position.law.title %></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <ul class="categorie-container">
                <% position.law.tag_list.each do |tag|%>
                  <%= link_to deputy_path(@deputy, tag: tag) do %>
                    <li class="categorie-label"><%= tag.split(" ").reject{ |word| word == "-"}.map(&:capitalize).unshift("#").join %></li>
                  <% end %>
                <% end %>
              </ul>
              <div class="modal-body">
                <p> <%= position.law.content %></p>
              </div>
              <div class="modal-footer d-flex justify-content-center">
                <a href="<%= position.law.ressource_link %>" target="blank" class="button button-primary">Voir plus sur Vie-publique.fr</a>
              </div>
            </div>
          </div>
        </div>

      </div>
      </div>
    <% end %>
  </div>

</div>