config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get '/sitemap', to: 'sitemaps#index', :defaults => {:format => 'xml'}
  # get 'laws/:id', to: 'laws#show'
  resources :laws, only: [:show, :new, :create]
  get 'votes/:id', to: 'votes#show'
  get '/dashboard', to: 'pages#dashboard'
  get '/get_followed_deputies', to: 'deputies#get_followed_deputies'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :deputies, only: [:show] do
    collection do
      get :results
    end
    member do
      get :like
      get :like_guest
      post :follow
      get :follow_guest
      get :is_followed
    end
  end

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/pages/dashboard.html.erb
  <div class="d-flex flex-column align-items-center mb-4"> 
    <h1 class="pb-3 pt-5">Bonjour <%= @user.email %></h1>
    <h2 class="pb-4">Les députés que vous suivez</h2>
  </div>
  <div class="d-flex justify-content-center dashboard-container ">
    <% @deputies.each do |deputy| %>
      <%= link_to deputy_path(deputy) do %>  
        <div class="deputy-card flex-column justify-content-between d-flex col-lg-2 col-md-6 col-sm-11 mx-3 px-0">
          <div class="avatar-container pt-4">
            <img src="<%= deputy.img %>" alt="" class="avatar-bordered">
            <h3><%= deputy.first_name %> <%= deputy.last_name %></h3>
          </div>
          <%= link_to unfollow_deputy_path(deputy), class: 'button button-danger width-grow' do %>
            Ne plus suivre
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/pages/home.html.erb
<div class="d-flex justify-content-center align-items-center home-container" data-user="<%= current_user ? true : false %>" style="background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), url(https://www.inegalites.fr/IMG/arton59.jpg);">
  <div class="d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex flex-column justify-content-center align-items-center background-home">
      <h1 class="home-h1">Découvrez <span class="underline-blue">qui est votre élu</span></h1>
      <h3 class="home-h3 md-col-12 lg-col-7"> Comprenez ses positions de vote sur les <span class="underline-red">sujets qui vous tiennent à coeur</span></h2>
    </div>
    <%= form_tag results_deputies_path, class:"d-flex col-10", method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        id: "location-search",
        placeholder: "Tapez votre adresse ou le nom de votre député..."
      %>
      <%= submit_tag "Rechercher", class: "btn btn-primary ml-2" %>
    <% end %>
  </div>
</div>


<div class="d-flex flex-column justify-content-center align-items-center">
  <h3 class="m-5 text-center black-h3"> Dernières lois analysées</h3>


  <% @laws.each do |law| %>
      <div class="law-card-home">
        <div class="law-card-home-details">
          <h3><%= law.title %></h3>
          <p class="mt-2 mb-2"><strong><%= law.current_status %> le <%= law.last_status_update %></strong>
            - <%= law.pour %> votes pour,
            <%= law.contre %> votes contre,
            <%= law.abstenu %> abstentions
          </p>
          <% if law.content == "" %>
            <a href="<%= law.ressource_link %>" class="more-info" target="blank">
              Plus d'informations
            </a>
          <% else %>
            <a href="" class="more-info" data-toggle="modal" data-target="#modal-<%= law.id %>">
              Plus d'informations
            </a>
          <% end %>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="modal-<%= law.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-image"></div>
            <div class="modal-content"><div>
              <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel"><%= law.title %></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <p> <%= law.content %></p>
              </div>
              <div class="modal-footer d-flex justify-content-center">
                <a href="<%= law.ressource_link %>" target="blank" class="button button-primary">Voir plus sur Vie-publique.fr</a>
              </div>
            </div>
          </div>
        </div>

      </div>
      </div>
    <% end %>
</div>